import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            <code className={styles.code}>InnerCalm server</code>
          </p>
          <div>
            <a
              href="https://innercalm.netlify.app"
            >
              INNERCALM
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <a
            href="https://innercalm.netlify.app"
            style={{ fontSize: "35px", cursor: "pointer",zIndex : "99999999", border :"2px solid white",
                  borderRadius : "30px", padding : "20px",boxShadow : "#000 10px 10px 10px", background : "black"
             }}
          >
            INNERCALM
          </a>
        </div>

        <div>

        </div>

      </main>
    </>
  )
}
